module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'auth',
        'course',
        'chapter',
        'quiz',
        'admin',
        'student',
        'chatbot',
        'gamification',
        'leaderboard',
        'infra',
        'deps',
      ],
    ],
    'scope-empty': [1, 'never'],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'chore',
        'style',
        'refactor',
        'ci',
        'test',
        'perf',
        'revert',
        'vercel',
      ],
    ],
  },
};
