## scp docker-compose.vps.yml root@72.62.125.129:/home/eduloca/web-lms/docker-compose.yml
## scp docker-compose.vps.yml hostinger-algoritme-eduloca:/home/eduloca/web-lms/docker-compose.yml
services:
  lms-web-app:
    image: farrelputras/lms-literasi-syariah-next:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
